# Generated by Django 5.1.3 on 2024-11-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_search_team',
            new_name='is_search_members',
        ),
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.competition'),
        ),
    ]
